// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axdxatmowftieqhilgto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZHhhdG1vd2Z0aWVxaGlsZ3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDU5NTcsImV4cCI6MjA4NzY4MTk1N30.8JtrnhXIH2EdXCtOW_Uoh923c-4YUw1dBoSUAcXthq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});